version: '2'

services:

  spark-submit:
    container_name: scraper-spark-submit
    image: bde2020/spark-submit:2.0.1-hadoop2.7
    environment:
      - constraint:node==slave3
    volumes:
      - /srv/sevod/sevod-scraper/assembly/target:/myapp
      - /srv/sevod/submit-conf:/spark/conf
    env_file:
      - ./scraper.env

  spark-master:
    container_name: scraper-spark-master
    hostname: scraper-spark-master
    image: bde2020/spark-master:2.0.1-hadoop2.7
    environment:
      - constraint:node==slave3
    ports:
      - "7077:7077"

  spark-worker:
    image: bde2020/spark-worker:2.0.1-hadoop2.7
    environment:
      - constraint:node==/slave\d/
      - affinity:container!=~*spark-worker*
      - SPARK_MASTER=scraper-spark-master:7077
    depends_on:
      - spark-master

  hdfs-namenode:
     image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
     container_name: scraper-hdfs-namenode
     environment:
        - CLUSTER_NAME=scraper-hdfs-cluster
        - "constraint:node==slave3"
     env_file:
        - ./hadoop.env
     volumes:
        - /srv/sevod/fedbenchdumps:/dumps
     ports:
        - "50070:50070"
        - "8020:8020"

  hdfs-datanode:
     image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
     environment:
        - constraint:node==/slave\d/
        - affinity:container!=~*hdfs-datanode*
     env_file:
        - ./hadoop.env
     depends_on:
        - hdfs-namenode


